"""Command-line interface for the resume parser framework.

This module provides a minimal submission-grade CLI that builds framework components,
parses a resume file, and prints structured JSON output to stdout.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import sys
from dataclasses import asdict
from collections.abc import Callable
from pathlib import Path
from typing import TypeVar

from app.extractors.base import ExtractionError, FieldExtractor
from app.extractors.email_extractor import EmailExtractor
from app.extractors.name_extractor import NameExtractor
from app.extractors.openai_llm_client import OpenAILLMClient
from app.extractors.skills_extractor import LLMClient, SkillsExtractor
from app.framework import ResumeParserFramework
from app.parsers.base import ParserError
from app.parsers.pdf_parser import PDFParser
from app.parsers.word_parser import WordParser
from app.resume_extractor import ResumeExtractor

logger = logging.getLogger(__name__)


class _FakeSkillsLLMClient(LLMClient):
    """Deterministic offline LLM client for demo and test-safe execution."""

    def complete(self, prompt: str) -> str:
        """Return deterministic skills inferred from resume text within the prompt.

        The implementation is intentionally simple and offline: it scans for common
        skill keywords and returns a JSON array string. If no keyword is matched, it
        falls back to a small default list to keep demo output predictable.

        Args:
            prompt: Prompt text generated by ``SkillsExtractor``.

        Returns:
            str: JSON string containing extracted skills.

        Raises:
            None.
        """

        catalog = [
            ("machine learning", "Machine Learning"),
            ("artificial intelligence", "Artificial Intelligence"),
            ("retrieval-augmented generation", "RAG"),
            ("rag", "RAG"),
            ("agentic", "Agentic Systems"),
            ("langchain", "LangChain"),
            ("langgraph", "LangGraph"),
            ("distilbert", "DistilBERT"),
            ("llm", "LLM"),
            ("python", "Python"),
            ("sql", "SQL"),
            ("postgresql", "PostgreSQL"),
            ("mysql", "MySQL"),
            ("redis", "Redis"),
            ("java", "Java"),
            ("javascript", "JavaScript"),
            ("typescript", "TypeScript"),
            ("react", "React"),
            ("node", "Node.js"),
            ("aws", "AWS"),
            ("gcp", "GCP"),
            ("docker", "Docker"),
            ("kubernetes", "Kubernetes"),
            ("pandas", "Pandas"),
            ("numpy", "NumPy"),
            ("tensorflow", "TensorFlow"),
            ("pytorch", "PyTorch"),
            ("scikit-learn", "Scikit-learn"),
            ("fastapi", "FastAPI"),
            ("django", "Django"),
            ("flask", "Flask"),
            ("oauth", "OAuth"),
            ("terraform", "Terraform"),
            ("jenkins", "Jenkins"),
            ("github actions", "GitHub Actions"),
            ("kafka", "Kafka"),
            ("rabbitmq", "RabbitMQ"),
            ("prometheus", "Prometheus"),
            ("grafana", "Grafana"),
            ("mlflow", "MLflow"),
            ("git", "Git"),
            ("c++", "C++"),
            ("go", "Go"),
        ]

        lowered = _skills_focused_text(prompt).lower()
        extracted = [label for token, label in catalog if token in lowered]
        if not extracted:
            extracted = ["Python", "LLM"]
        return json.dumps(extracted)


def _skills_focused_text(prompt: str) -> str:
    """Prefer text near skill-oriented headings before falling back to full prompt text.

    This helper biases extraction toward the section most likely to list technologies.

    Args:
        prompt: Full skills extraction prompt.

    Returns:
        str: Skill-focused text segment when detected, otherwise full prompt.

    Raises:
        None.
    """

    patterns = (
        r"(skill set.*?)(professional experience|experience|education|$)",
        r"(technical skills.*?)(experience|education|$)",
        r"(skills.*?)(experience|education|$)",
    )
    for pattern in patterns:
        match = re.search(pattern, prompt, flags=re.IGNORECASE | re.DOTALL)
        if match:
            return match.group(1)
    return prompt


class _StubSkillsLLMClient(LLMClient):
    """Minimal stub LLM client that returns an empty skills array."""

    def complete(self, prompt: str) -> str:
        """Return an empty JSON array for skill extraction.

        This keeps the skills field deterministic when LLM extraction is disabled.

        Args:
            prompt: Prompt text generated by ``SkillsExtractor``.

        Returns:
            str: Empty JSON array payload.

        Raises:
            None.
        """

        _ = prompt
        return "[]"


class _StubNameExtractor(FieldExtractor[str | None]):
    """Stub name extractor that intentionally returns no value."""

    def extract(self, text: str) -> str | None:
        """Return ``None`` regardless of input text.

        This strategy exists only for deterministic baseline and debugging modes.

        Args:
            text: Resume plain text.

        Returns:
            str | None: Always ``None``.

        Raises:
            None.
        """

        return None if text else None


class _StubEmailExtractor(FieldExtractor[str | None]):
    """Stub email extractor that intentionally returns no value."""

    def extract(self, text: str) -> str | None:
        """Return ``None`` regardless of input text.

        This strategy exists only for deterministic baseline and debugging modes.

        Args:
            text: Resume plain text.

        Returns:
            str | None: Always ``None``.

        Raises:
            None.
        """

        return None if text else None


T = TypeVar("T")


def _openai_llm_factory() -> LLMClient:
    """Create OpenAI-backed LLM client using environment-provided model configuration.

    The model name is read from ``OPENAI_MODEL`` with a safe default.

    Args:
        None.

    Returns:
        LLMClient: OpenAI-backed client implementation.

    Raises:
        ValueError: If OpenAI credentials are missing.
        RuntimeError: If OpenAI SDK is not available.
    """

    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    logger.info("Using OpenAI-backed skills strategy with model '%s'", model)
    return OpenAILLMClient(model=model)


NAME_EXTRACTOR_FACTORIES: dict[str, Callable[[], FieldExtractor[str | None]]] = {
    "rule": NameExtractor,
    "stub": _StubNameExtractor,
}

EMAIL_EXTRACTOR_FACTORIES: dict[str, Callable[[], FieldExtractor[str | None]]] = {
    "regex": EmailExtractor,
    "stub": _StubEmailExtractor,
}

# Skills strategies are resolved by choosing the LLM client implementation.
SKILLS_LLM_FACTORIES: dict[str, Callable[[], LLMClient]] = {
    "fake": _FakeSkillsLLMClient,
    "stub": _StubSkillsLLMClient,
    "llm": _openai_llm_factory,
}


def _resolve_factory(mode: str, factories: dict[str, Callable[[], T]], kind: str) -> T:
    """Resolve and execute a strategy factory by mode name.

    Unknown modes are reported with available options for fast recovery.

    Args:
        mode: User-selected strategy mode.
        factories: Mapping of mode names to zero-argument constructors.
        kind: Human-readable strategy category for diagnostics.

    Returns:
        T: Concrete strategy instance resolved from the mode mapping.

    Raises:
        ValueError: If mode is not registered in the provided factories.
    """

    factory = factories.get(mode)
    if factory is None:
        available = ", ".join(sorted(factories))
        raise ValueError(f"Unknown {kind} mode '{mode}'. Available: {available}")
    return factory()


def _configure_logging(debug: bool) -> None:
    """Configure process-level logging for CLI runs.

    The debug flag is scoped to application logs. Third-party libraries stay quiet unless
    explicitly reconfigured, preventing excessive parser internals from polluting output.

    Args:
        debug: When ``True``, application log level is set to ``DEBUG``.

    Returns:
        None.

    Raises:
        None.
    """

    level = logging.INFO
    logging.basicConfig(
        level=level,
        format="%(levelname)s %(name)s: %(message)s",
    )
    app_logger = logging.getLogger("app")
    app_logger.setLevel(logging.DEBUG if debug else logging.INFO)

    # Keep verbose parser internals readable even when app debug mode is enabled.
    logging.getLogger("pdfminer").setLevel(logging.WARNING)
    logging.getLogger("openai").setLevel(logging.WARNING)
    logging.getLogger("httpx").setLevel(logging.WARNING)


def _load_env_file(file_path: str = ".env") -> None:
    """Load environment variables from a dotenv file when present.

    Behavior:
    - Missing file is ignored.
    - Existing process environment variables are not overwritten.
    - Lines must follow ``KEY=VALUE`` format (comments and blanks are ignored).

    Args:
        file_path: Path to dotenv file, defaults to ``.env``.

    Returns:
        None.

    Raises:
        None.
    """

    path = Path(file_path)
    if not path.exists():
        logger.debug("No .env file found at %s", path)
        return

    logger.debug("Loading environment variables from %s", path)
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            logger.warning("Ignoring malformed .env line %d: %s", line_number, raw_line)
            continue

        key, value = line.split("=", maxsplit=1)
        key = key.strip()
        value = value.strip().strip("'\"")
        if not key:
            logger.warning("Ignoring malformed .env line %d with empty key", line_number)
            continue

        os.environ.setdefault(key, value)
    logger.info("Environment bootstrap complete (.env + exported vars)")


def build_framework(name_mode: str, email_mode: str, skills_mode: str) -> ResumeParserFramework:
    """Build a fully wired framework instance for CLI execution.

    Strategies are resolved from mode-to-factory maps for pluggable composition.

    Args:
        name_mode: Strategy mode for name extraction. Supported: ``rule``, ``stub``.
        email_mode: Strategy mode for email extraction. Supported: ``regex``, ``stub``.
        skills_mode: Strategy mode for skill extraction. Supported values are
            ``"fake"``, ``"stub"``, and ``"llm"``.

    Returns:
        A configured ``ResumeParserFramework`` instance.

    Raises:
        ValueError: If a requested strategy mode is unknown.
        RuntimeError: If runtime dependencies for selected strategies are unavailable.
    """

    logger.info(
        "Building framework with modes: name=%s email=%s skills=%s",
        name_mode,
        email_mode,
        skills_mode,
    )
    name_extractor = _resolve_factory(name_mode, NAME_EXTRACTOR_FACTORIES, "name strategy")
    email_extractor = _resolve_factory(email_mode, EMAIL_EXTRACTOR_FACTORIES, "email strategy")
    llm_client = _resolve_factory(skills_mode, SKILLS_LLM_FACTORIES, "skills strategy")

    field_extractors = {
        "name": name_extractor,
        "email": email_extractor,
        "skills": SkillsExtractor(llm_client=llm_client),
    }
    resume_extractor = ResumeExtractor(field_extractors)

    parsers = [PDFParser(), WordParser()]
    logger.debug(
        "Configured parser candidates: %s",
        [parser.__class__.__name__ for parser in parsers],
    )
    return ResumeParserFramework(parsers, resume_extractor)


def _build_argument_parser() -> argparse.ArgumentParser:
    """Create and configure the CLI argument parser.

    The parser exposes runtime strategy flags and debug controls.

    Args:
        None.

    Returns:
        argparse.ArgumentParser: Configured parser instance for CLI options.

    Raises:
        None.
    """

    parser = argparse.ArgumentParser(
        description="Parse a resume file into structured JSON output."
    )
    parser.add_argument("--file", required=True, help="Path to a resume file (.pdf or .docx)")
    parser.add_argument(
        "--name-mode",
        choices=("rule", "stub"),
        default="rule",
        help="Name extraction mode: rule (default) or stub (always None)",
    )
    parser.add_argument(
        "--email-mode",
        choices=("regex", "stub"),
        default="regex",
        help="Email extraction mode: regex (default) or stub (always None)",
    )
    parser.add_argument(
        "--skills-mode",
        choices=("fake", "stub", "llm"),
        default="fake",
        help="Skills extraction mode: fake, stub, or llm (OpenAI-backed)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging for troubleshooting parser and extraction flows",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the CLI and return a process-compatible exit code.

    Exit codes:
        0: Success.
        1: Parser or extraction runtime error.
        2: User input/argument error.

    Args:
        argv: Optional list of CLI arguments. Uses ``sys.argv`` when ``None``.

    Returns:
        int: Process-compatible exit status code.

    Raises:
        None.
    """

    parser = _build_argument_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        code = exc.code
        return code if isinstance(code, int) else 2

    _configure_logging(args.debug)
    _load_env_file()
    logger.info("Starting resume parsing CLI for file: %s", args.file)

    try:
        framework = build_framework(args.name_mode, args.email_mode, args.skills_mode)
    except (ValueError, RuntimeError) as exc:
        if args.debug:
            logger.exception("Failed to build framework")
        else:
            logger.error("%s", exc)
        print(f"{exc.__class__.__name__}: {exc}", file=sys.stderr)
        return 1

    try:
        result = framework.parse_resume(args.file)
    except (ParserError, ExtractionError) as exc:
        if args.debug:
            logger.exception("Runtime parsing/extraction failure")
        else:
            logger.error("%s", exc)
        print(f"{exc.__class__.__name__}: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
